apiVersion: v1    #目前api server所能識別的內容為第一代
kind: Pod
metadata:
  name: pod-fbs   #設定pod名字
  labels:
    name: pod-fbs #設定pod標籤名字
spec:             #設定pod的內部規格
  containers:
  - name: myfbs
    image: localhost/alp.myfbs
    imagePullPolicy: IfNotPresent   #五顆星重點，如果已經有下載上面的image，就不用再次下載
   #imagePullPolicy: Never          #表示絕不從外網下載，在自己已經產生並裝好image的情況下使用，N一定要大寫
    ports:
     - containerPort: 4000
